# Day 9 – Processed E-commerce Dataset

## Pandas Merge, Concatenate, Apply, and DateTime Operations

This notebook combines the provided **Orders**, **Customers**, and **Products** datasets into one clean processed e-commerce dataset.

### Main tasks
- Load three CSV datasets with Pandas
- Combine DataFrames using `concat()`
- Combine related datasets using `merge()`
- Create useful columns using `apply()`
- Convert order dates to DateTime
- Extract year, month, day, and day-of-week information
- Organize the final DataFrame
- Export the processed dataset as a CSV file

## 1. Import Pandas and Load the Three Datasets

In [1]:
import pandas as pd

orders = pd.read_csv("Day9_Orders.csv")
customers = pd.read_csv("Day9_Customers.csv")
products = pd.read_csv("Day9_Products.csv")

print("Orders shape:", orders.shape)
print("Customers shape:", customers.shape)
print("Products shape:", products.shape)

Orders shape: (120, 7)
Customers shape: (30, 5)
Products shape: (20, 5)

## 2. Inspect the Input Datasets

In [2]:
print("Orders:")
display(orders.head())

print("Customers:")
display(customers.head())

print("Products:")
display(products.head())

Orders:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

Customers:

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

Products:

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

## 3. Combine DataFrames Using `concat()`

`concat()` is demonstrated by splitting the Orders DataFrame into two parts and combining them vertically again. This illustrates row-wise concatenation.

In [3]:
orders_part1 = orders.iloc[:60].copy()
orders_part2 = orders.iloc[60:].copy()

orders_combined = pd.concat(
    [orders_part1, orders_part2],
    ignore_index=True
)

print("First part shape:", orders_part1.shape)
print("Second part shape:", orders_part2.shape)
print("Combined shape:", orders_combined.shape)

display(orders_combined.head())

First part shape: (60, 7)
Second part shape: (60, 7)
Combined shape: (120, 7)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

## 4. Merge Orders with Products

The `Product_ID` column is the common key between Orders and Products. A left merge keeps every order and adds the corresponding product information.

In [4]:
orders_products = orders_combined.merge(
    products,
    on="Product_ID",
    how="left",
    validate="many_to_one"
)

print("Shape after merging Orders and Products:", orders_products.shape)
display(orders_products.head())

Shape after merging Orders and Products: (120, 11)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Coffee Maker,Home & Kitchen,3499,HomeBrew

## 5. Merge with Customers

The `Customer_ID` column connects the order information with the Customers DataFrame.

In [5]:
processed = orders_products.merge(
    customers,
    on="Customer_ID",
    how="left",
    validate="many_to_one"
)

print("Shape after merging all three datasets:", processed.shape)
display(processed.head())

Shape after merging all three datasets: (120, 15)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Product_Name,Category,Unit_Price,Brand,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Cricket Bat,Sports,2499,BatPro,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Wireless Mouse,Electronics,899,TechGear,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Smart Watch,Electronics,3299,FitTech,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Machine Learning Basics,Books,999,AIPress,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Coffee Maker,Home & Kitchen,3499,HomeBrew,Reyansh Jain,Kolkata,East,New

## 6. Check the Merge Result

In [6]:
print("Missing product names:", processed["Product_Name"].isna().sum())
print("Missing customer names:", processed["Customer_Name"].isna().sum())

print("\nColumns after merging:")
print(processed.columns.tolist())

Missing product names: 0
Missing customer names: 0

Columns after merging:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status', 'Product_Name', 'Category', 'Unit_Price', 'Brand', 'Customer_Name', 'City', 'Region', 'Membership_Type']

## 7. Convert Order Date to DateTime

The Order_Date column is converted from text to Pandas DateTime so that date components can be extracted easily.

In [7]:
processed["Order_Date"] = pd.to_datetime(processed["Order_Date"])

print("Order_Date data type:", processed["Order_Date"].dtype)
display(processed[["Order_ID", "Order_Date"]].head())

Order_Date data type: datetime64[ns]

  Order_ID Order_Date
0    O0001 2026-02-19
1    O0002 2026-01-25
2    O0003 2026-02-26
3    O0004 2026-03-04
4    O0005 2026-03-29

## 8. Extract Date Information

Using the Pandas `.dt` accessor, we extract:
- Year
- Month number
- Month name
- Day of the month
- Day of the week

In [8]:
processed["Order_Year"] = processed["Order_Date"].dt.year
processed["Order_Month"] = processed["Order_Date"].dt.month
processed["Order_Month_Name"] = processed["Order_Date"].dt.month_name()
processed["Order_Day"] = processed["Order_Date"].dt.day
processed["Order_Day_Name"] = processed["Order_Date"].dt.day_name()

display(
    processed[
        [
            "Order_ID",
            "Order_Date",
            "Order_Year",
            "Order_Month",
            "Order_Month_Name",
            "Order_Day",
            "Order_Day_Name"
        ]
    ].head()
)

,Order_ID,Order_Date,Order_Year,Order_Month,Order_Month_Name,Order_Day,Order_Day_Name
0,O0001,2026-02-19,2026,2,February,19,Thursday
1,O0002,2026-01-25,2026,1,January,25,Sunday
2,O0003,2026-02-26,2026,2,February,26,Thursday
3,O0004,2026-03-04,2026,3,March,4,Wednesday
4,O0005,2026-03-29,2026,3,March,29,Sunday

## 9. Create Useful Columns Using `apply()`

First, calculate the sales amount from quantity and unit price. Then use `apply()` to classify each order as Low, Medium, or High Value.

In [9]:
processed["Sales_Amount"] = processed.apply(
    lambda row: row["Quantity"] * row["Unit_Price"],
    axis=1
)

processed["Order_Size"] = processed["Sales_Amount"].apply(
    lambda amount: "High Value" if amount >= 5000
    else "Medium Value" if amount >= 2000
    else "Low Value"
)

display(
    processed[
        [
            "Order_ID",
            "Product_Name",
            "Quantity",
            "Unit_Price",
            "Sales_Amount",
            "Order_Size"
        ]
    ].head(10)
)

,Order_ID,Product_Name,Quantity,Unit_Price,Sales_Amount,Order_Size
0,O0001,Cricket Bat,2,2499,4998,Medium Value
1,O0002,Wireless Mouse,2,899,1798,Low Value
2,O0003,Smart Watch,1,3299,3299,Medium Value
3,O0004,Machine Learning Basics,3,999,2997,Medium Value
4,O0005,Coffee Maker,5,3499,17495,High Value
5,O0006,Football,3,799,2397,Medium Value
6,O0007,Wireless Mouse,3,899,2697,Medium Value
7,O0008,Power Bank,4,1199,4796,Medium Value
8,O0009,Coffee Maker,2,3499,6998,High Value
9,O0010,Power Bank,2,1199,2398,Medium Value

## 10. Create a Clean Final DataFrame

The final dataset is organized so that order, date, customer, product, sales, payment, and status information are easy to understand.

In [10]:
processed = processed[
    [
        "Order_ID",
        "Order_Date",
        "Order_Year",
        "Order_Month",
        "Order_Month_Name",
        "Order_Day",
        "Order_Day_Name",
        "Customer_ID",
        "Customer_Name",
        "City",
        "Region",
        "Membership_Type",
        "Product_ID",
        "Product_Name",
        "Category",
        "Brand",
        "Unit_Price",
        "Quantity",
        "Sales_Amount",
        "Order_Size",
        "Payment_Method",
        "Order_Status"
    ]
]

print("Final shape:", processed.shape)
display(processed.head())

Final shape: (120, 22)

,Order_ID,Order_Date,Order_Year,Order_Month,Order_Month_Name,Order_Day,Order_Day_Name,Customer_ID,Customer_Name,City,...,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Sales_Amount,Order_Size,Payment_Method,Order_Status
0,O0001,2026-02-19,2026,2,February,19,Thursday,C027,Harsh Vardhan,Noida,...,P019,Cricket Bat,Sports,BatPro,2499,2,4998,Medium Value,Credit Card,Delivered
1,O0002,2026-01-25,2026,1,January,25,Sunday,C006,Ishita Gupta,Bengaluru,...,P003,Wireless Mouse,Electronics,TechGear,899,2,1798,Low Value,Debit Card,Delivered
2,O0003,2026-02-26,2026,2,February,26,Thursday,C015,Karan Joshi,Chandigarh,...,P004,Smart Watch,Electronics,FitTech,3299,1,3299,Medium Value,Cash on Delivery,Delivered
3,O0004,2026-03-04,2026,3,March,4,Wednesday,C024,Maryam Khan,Hyderabad,...,P015,Machine Learning Basics,Books,AIPress,999,3,2997,Medium Value,Net Banking,Delivered
4,O0005,2026-03-29,2026,3,March,29,Sunday,C025,Reyansh Jain,Kolkata,...,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,5,17495,High Value,Credit Card,Delivered

## 11. Check the Final Dataset

In [11]:
print("Data types:")
print(processed.dtypes)

print("\nMissing values:")
print(processed.isna().sum())

print("\nDuplicate rows:", processed.duplicated().sum())

Data types:
Order_ID                    object
Order_Date          datetime64[ns]
Order_Year                   int32
Order_Month                  int32
Order_Month_Name            object
Order_Day                    int32
Order_Day_Name              object
Customer_ID                 object
Customer_Name               object
City                        object
Region                      object
Membership_Type             object
Product_ID                  object
Product_Name                object
Category                    object
Brand                       object
Unit_Price                   int64
Quantity                     int64
Sales_Amount                 int64
Order_Size                  object
Payment_Method              object
Order_Status                object
dtype: object

Missing values:
Order_ID            0
Order_Date          0
Order_Year          0
Order_Month         0
Order_Month_Name    0
Order_Day           0
Order_Day_Name      0
Customer_ID         0
Customer_Name       0
City                0
Region              0
Membership_Type     0
Product_ID          0
Product_Name        0
Category            0
Brand               0
Unit_Price          0
Quantity            0
Sales_Amount        0
Order_Size          0
Payment_Method      0
Order_Status        0
dtype: int64

Duplicate rows: 0

## 12. Preview Selected Processed Information

In [12]:
display(
    processed[
        [
            "Order_ID",
            "Order_Date",
            "Customer_Name",
            "City",
            "Product_Name",
            "Category",
            "Quantity",
            "Sales_Amount",
            "Payment_Method",
            "Order_Status"
        ]
    ].head(10)
)

,Order_ID,Order_Date,Customer_Name,City,Product_Name,Category,Quantity,Sales_Amount,Payment_Method,Order_Status
0,O0001,2026-02-19,Harsh Vardhan,Noida,Cricket Bat,Sports,2,4998,Credit Card,Delivered
1,O0002,2026-01-25,Ishita Gupta,Bengaluru,Wireless Mouse,Electronics,2,1798,Debit Card,Delivered
2,O0003,2026-02-26,Karan Joshi,Chandigarh,Smart Watch,Electronics,1,3299,Cash on Delivery,Delivered
3,O0004,2026-03-04,Maryam Khan,Hyderabad,Machine Learning Basics,Books,3,2997,Net Banking,Delivered
4,O0005,2026-03-29,Reyansh Jain,Kolkata,Coffee Maker,Home & Kitchen,5,17495,Credit Card,Delivered
5,O0006,2026-02-09,Rohan Mehta,Mumbai,Football,Sports,3,2397,UPI,Delivered
6,O0007,2026-02-10,Vivaan Kapoor,Jaipur,Wireless Mouse,Electronics,3,2697,UPI,Delivered
7,O0008,2026-03-27,Priya Menon,Chennai,Power Bank,Electronics,4,4796,Debit Card,Delivered
8,O0009,2026-03-13,Maryam Khan,Hyderabad,Coffee Maker,Home & Kitchen,2,6998,UPI,Cancelled
9,O0010,2026-03-05,Fatima Noor,Srinagar,Power Bank,Electronics,2,2398,Debit Card,Shipped

## 13. Export the Processed Dataset

The final cleaned and enriched DataFrame is exported as `Processed_Ecommerce_Dataset.csv`.

In [13]:
output_file = "Processed_Ecommerce_Dataset.csv"

processed.to_csv(output_file, index=False)

print(f"Processed dataset exported successfully: {output_file}")

Processed dataset exported successfully: Processed_Ecommerce_Dataset.csv

## 14. Basic Observations

These observations are calculated from the processed dataset.

In [14]:
total_sales = processed["Sales_Amount"].sum()
total_quantity = processed["Quantity"].sum()
top_category = processed.groupby("Category")["Sales_Amount"].sum().idxmax()
top_city = processed.groupby("City")["Sales_Amount"].sum().idxmax()
top_product = processed.groupby("Product_Name")["Sales_Amount"].sum().idxmax()
top_payment = processed.groupby("Payment_Method")["Sales_Amount"].sum().idxmax()

print(f"1. The processed dataset contains {processed.shape[0]} order records and {processed.shape[1]} columns.")
print(f"2. Total sales value calculated from Quantity × Unit_Price is ₹{total_sales:,.2f}.")
print(f"3. Total quantity of products ordered is {total_quantity}.")
print(f"4. The category with the highest total sales is {top_category}.")
print(f"5. The city with the highest total sales is {top_city}.")
print(f"6. The product with the highest total sales is {top_product}.")
print(f"7. The payment method with the highest total sales is {top_payment}.")

1. The processed dataset contains 120 order records and 22 columns.
2. Total sales value calculated from Quantity × Unit_Price is ₹741,507.00.
3. Total quantity of products ordered is 343.
4. The category with the highest total sales is Home & Kitchen.
5. The city with the highest total sales is Srinagar.
6. The product with the highest total sales is Air Fryer.
7. The payment method with the highest total sales is Credit Card.

## 15. Final Processed Dataset

The complete processed DataFrame is displayed below.

In [15]:
processed

,Order_ID,Order_Date,Order_Year,Order_Month,Order_Month_Name,Order_Day,Order_Day_Name,Customer_ID,Customer_Name,City,...,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Sales_Amount,Order_Size,Payment_Method,Order_Status
0,O0001,2026-02-19,2026,2,February,19,Thursday,C027,Harsh Vardhan,Noida,...,P019,Cricket Bat,Sports,BatPro,2499,2,4998,Medium Value,Credit Card,Delivered
1,O0002,2026-01-25,2026,1,January,25,Sunday,C006,Ishita Gupta,Bengaluru,...,P003,Wireless Mouse,Electronics,TechGear,899,2,1798,Low Value,Debit Card,Delivered
2,O0003,2026-02-26,2026,2,February,26,Thursday,C015,Karan Joshi,Chandigarh,...,P004,Smart Watch,Electronics,FitTech,3299,1,3299,Medium Value,Cash on Delivery,Delivered
3,O0004,2026-03-04,2026,3,March,4,Wednesday,C024,Maryam Khan,Hyderabad,...,P015,Machine Learning Basics,Books,AIPress,999,3,2997,Medium Value,Net Banking,Delivered
4,O0005,2026-03-29,2026,3,March,29,Sunday,C025,Reyansh Jain,Kolkata,...,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,5,17495,High Value,Credit Card,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,O0116,2026-02-19,2026,2,February,19,Thursday,C025,Reyansh Jain,Kolkata,...,P010,Electric Kettle,Home & Kitchen,KitchenPro,1499,1,1499,Low Value,Net Banking,Delivered
116,O0117,2026-02-21,2026,2,February,21,Saturday,C019,Yusuf Dar,Srinagar,...,P015,Machine Learning Basics,Books,AIPress,999,3,2997,Medium Value,Cash on Delivery,Shipped
117,O0118,2026-03-09,2026,3,March,9,Monday,C025,Reyansh Jain,Kolkata,...,P016,Atomic Habits,Books,MindReads,599,4,2396,Medium Value,Credit Card,Delivered
118,O0119,2026-02-03,2026,2,February,3,Tuesday,C015,Karan Joshi,Chandigarh,...,P019,Cricket Bat,Sports,BatPro,2499,2,4998,Medium Value,Debit Card,Delivered
119,O0120,2026-01-21,2026,1,January,21,Wednesday,C013,Rahul Das,Kolkata,...,P020,Dumbbell Set,Sports,StrongFit,1999,1,1999,Low Value,Cash on Delivery,Cancelled

## Conclusion

The three source datasets were successfully loaded and combined. `concat()` was used to demonstrate vertical DataFrame combination, while `merge()` joined Orders with Products and Customers using their related IDs.

`apply()` was used to create useful derived columns, including Sales_Amount and Order_Size. DateTime operations were used to convert Order_Date and extract year, month, day, month name, and day-of-week information.

The final clean dataset was exported as `Processed_Ecommerce_Dataset.csv`.